name = "Stochastic Load Modelling"

[data]

    [data.load_measurements]
    path = "load_data\\sample_load_data.xlsx"
    date_format = "%H"
    first_date_iso = "2020-01-01"
    
    # For excel-files:
    sheet = 0
    time_column = 0
    data_column = 1
    vertical_data = "True"


    [data.temperature_measurements]
    path = "temperatur_data\\Temperatur_Strømtangen_fyr_2018-2020.xlsx"
    date_format = "%d.%m.%Y"
    first_date_iso = "2018-01-01"

    # For excel-files:
    sheet = 0
    time_column = 2
    data_column = 3
    vertical_data = "True"


    [data.temperature_measurements_historical]
    path = "temperatur_data\\Temperatur_Strømtangen_fyr_2000-2019.xlsx"
    date_format = "%d.%m.%Y"
    first_date_iso = "2000-01-01"

    # For excel-files:
    sheet = 0
    time_column = 2
    data_column = 3
    vertical_data = "True"


[preprocessing]

# Any non-zero value will indicate the chosen preprocessing step is computed
remove_NaN_and_None = "True"
correct_for_temperature = "True"
k_temperature_coefficient = 0.1
x_temperature_sensitivity = 0.05

[modelling]

chosen_model = "toenne"

    [modelling.toenne]
    max_or_average_variation_calculation = "average"
    variation_values_alternative = "B"  # As presented in Tønne, A: monthly and by workday/weekend, multiplicative, B: workday/weekend monthly
    histogram_periods = 1   # As presented in WP1_pilot_Stokastisk_lastmodellering, 
    stochastic_source = "error_histogram"   # Chosen way of generatic stochastic model, either from "error_histogram" or "distribution_fitting"